// output/VueJS-Trello-Board/src/components/column/Column.vue
<script setup lang="js">
import { Ellipsis, Plus } from 'lucide-vue-next';


const { column, selectColumnId } = defineProps({
  column: {
    type: Object,
    required: true
  },
  selectColumnId: {
    type: String,
  }
})

defineEmits(['openEditColumnModal'])
</script>

<template>
  <div class="flex items-start gap-4 sm:gap-6 h-[calc(100vh-120px)]">
    <div class="column w-[260px] sm:w-72 shrink-0 ">
      <div class="column-inner rounded-2xl overflow-hidden bg-amber-100/80 border border-amber-200  shadow-[0_18px_40px_rgba(15,23,42,0.18)]">
        <div
          class="column-header flex items-center justify-between gap-2 px-3 sm:px-4 py-2.5 sm:py-3 bg-amber-300 text-amber-950 font-semibold column-drag-area cursor-grab active:cursor-grabbing select-none">
          <p class="column-title text-sm font-bold sm:text-[15px] leading-tight truncate max-w-[90%]">
            {{ column.name }}
          </p>
          <Ellipsis size="40"
            class="no-drag p-1.5 rounded-full cursor-pointer text-amber-900/80 hover:bg-amber-200/80 transition-colors"
            :class="{ 'bg-amber-100': column.id === selectColumnId }"
            @click.stop="$emit('openEditColumnModal', column, $event)" />
        </div>
        <div class="column-body bg-amber-50/80">
          <slot></slot>
        </div>
      </div>
    </div>
  </div>
</template>

// output/mini-trello-project/src/components/column/Column.jsx
import { GripVertical, Trash2 } from "lucide-react";
import TaskCard from "../task-card/TaskCard";

import AddTaskCard from "../task-card/AddTaskCard";


const Column = ({ column, tasks, onDeleteColumn, onAddTask, onDeleteTask, handleOpenModal }) => {

  return (
    <div className="bg-gray-50 dark:bg-black text-black dark:text-white border border-black dark:border-white

     rounded-xl p-4 w-80 flex-shrink-0 h-fit">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <GripVertical size={18} className="text-gray-400 cursor-grab" />
          <h3 className="font-semibold text-base">{column.title}</h3>
          <span className="text-xs bg-gray-200 dark:bg-gray-800 px-2 py-0.5 rounded-full font-medium">
            {tasks.length}
          </span>
        </div>
        <button
          onClick={() => onDeleteColumn(column.id)}
          className="text-gray-500 hover:text-red-500 transition-colors"
        >
          <Trash2 size={20} />
        </button>
      </div>
      
      <div className="space-y-3 max-h-[calc(100vh-220px)] overflow-y-auto pr-1 scrollbar-thin">
        {tasks.map(task => (
          <TaskCard
            key={task.id}
            task={task}
            columnId = {column.id}
            onDeleteTask={onDeleteTask}
            handleOpenModal={handleOpenModal}
          />
        ))}
        <AddTaskCard columnId= {column.id} onAddTask={onAddTask}/>
      </div>
    </div>
  );
};

export default Column;
