// output/VueJS-Trello-Board/src/components/column/ModalEditColumn.vue
<script setup lang="js">
import { ref, computed, watch } from "vue"
import { Copy, Trash2, X } from "lucide-vue-next"
import { caculatePositionModal } from "../../utils/caculatePositionModal"
import { debounce } from "lodash-es"

const props = defineProps({
  selectColumn: {
    type: Object,
    required: true,
  },
  modalPosition: {
    type: Object,
    required: true,
  },
})

const emit = defineEmits([
  "closeEditColumnModal",
  "handleDeleteColumn",
  "handleEditColumn",
])

const inputName = ref(props.selectColumn.name)

const modalSize = {
  width: 250,
  height: 300,
}

const position = computed(() =>
  caculatePositionModal(props.modalPosition, modalSize, 20)
)

const modalStyles = computed(() => ({
  top: position.value.top + "px",
  left: position.value.left + "px",
  width: modalSize.width + "px",
  height: modalSize.height + "px",
}))

const debouncedEmit = debounce((newName) => {
  emit("handleEditColumn", newName, props.selectColumn.id)
}, 600)

watch(inputName, (newName) => {
  debouncedEmit(newName)
})

watch(
  () => props.selectColumn,
  (col) => {
    if (col) inputName.value = col.name
  },
  { immediate: false }
)

const handleClose = () => emit("closeEditColumnModal")
const handleDelete = () => emit("handleDeleteColumn", props.selectColumn.id)
</script>

<template>
  <div class="fixed inset-0 z-50">
    <div class="absolute inset-0 bg-app-overlay" @click="handleClose"></div>
    <div
      class="absolute z-50 flex flex-col rounded-2xl  shadow-[0_18px_40px_rgba(15,23,42,0.18)] bg-app-bg-modal  border border-app-border-column overflow-hidden text-app-text-main"
      :style="modalStyles" role="dialog" aria-modal="true">
      <div
        class="flex items-center justify-between gap-3 px-4 py-3 border-b border-app-border-column bg-app-brand-soft">
        <h3 class="text-sm font-semibold">Chỉnh sửa cột</h3>
        <button type="button"
          class="no-drag inline-flex h-7 w-7 items-center justify-center rounded-full text-app-text-sub hover:bg-app-bg-board hover:text-app-text-main transition-colors"
          @click.stop="handleClose">
          <X class="w-4 h-4" />
        </button>
      </div>
      <div class="flex-1 px-4 py-3 space-y-4 text-sm overflow-y-auto">
        <div>
          <label class="block text-xs font-medium text-app-text-sub mb-1.5">
            Tên cột
          </label>
          <input v-model="inputName" type="text" placeholder="Nhập tên cột"
            class="w-full px-3 py-2 text-sm rounded-xl border border-app-border-column bg-app-bg-task text-app-text-main placeholder:text-app-text-muted focus:outline-none focus:ring-2 focus:ring-app-brand focus:border-app-brand transition-shadow" />
        </div>
        <ul class="space-y-1.5 text-sm">
          <li>
            <button type="button"
              class="w-full flex items-center gap-2 px-3 py-2 rounded-xl text-app-text-main bg-app-brand-soft hover:bg-app-brand-strong transition-colors">
              <Copy class="w-4 h-4" />
              <span>Nhân đôi cột</span>
            </button>
          </li>
          <li>
            <button type="button"
              class="w-full flex items-center gap-2 px-3 py-2 rounded-xl bg-app-danger text-white hover:bg-app-danger/60 transition-colors"
              @click="handleDelete">
              <Trash2 class="w-4 h-4" />
              <span>Xóa danh sách</span>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

// output/mini-trello-project/src/components/column/ModalEditColumn.jsx
import { useState, useEffect, useRef, useMemo } from "react";
import { createPortal } from "react-dom";
import { X, Copy, Trash2 } from "lucide-react";
import { useContext } from "react";
import { BoardContext } from "../../contexts/boardContext";
import { caculatePositionModal } from "../../utils/caculatePositionModal";

function ModalEditColumn({ isOpen, column, rect }) {
  const { closeEditColumn, handleUpdateColumn, handleDeleteColumn } = useContext(BoardContext);

  const [title, setTitle] = useState(column.title);
  const [oldTitle, setOldTitle] = useState(column.title);
  const modalRef = useRef(null);

  // tính vị trí để hiển trị modal
  const position = useMemo(() => {
    return caculatePositionModal(
      { x: rect.x, y: rect.y },
      { width: 300, height: 250 }
    );
  }, [rect]);

 
  const onDeleTeColumn = () => {
    handleDeleteColumn(column.id);
    closeEditColumn();
  };

  const handleChangeTitle = () => {
    const newTitle = title.trim();
    if (newTitle) {
      handleUpdateColumn({ title: newTitle }, column.id);
    } else {
      setTitle(oldTitle);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter") e.target.blur();
  };

  useEffect(() => {
    if (title) setOldTitle(title);
  }, [title]);


  useEffect(() => {
    const handleClickOutside = (e) => {
      if (modalRef.current && !modalRef.current.contains(e.target)) {
        closeEditColumn();
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  if (!isOpen) return null;

  return createPortal(
    <>
      <div
        ref={modalRef}
        className="fixed z-50 animate-fadeIn text-black dark:text-white
        will-change-transform bg-[rgb(146,221,255)]  dark:bg-[rgb(11,74,48)]
          rounded-lg shadow-2xl w-[300px] h-[250] overflow-hidden"
        style={{
          top: `${position.top + 20}px`,
          left: `${position.left}px`,
        }}
      >
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-700 dark:border-gray-300">
          <h3 className="text-sm font-semibold ">
            Thao tác danh sách
          </h3>
          <button
            onClick={closeEditColumn}
            className=" hover:bg-gray-300  rounded transition-colors"
          >
            <X />
          </button>
        </div>
        <div className="p-4">
          <div className="mb-4">
            <label
              htmlFor="columnName"
              className="block text-xs font-semibold mb-2"
            >
              Tên danh sách
            </label>
            <input
              id="columnName"
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              onBlur={handleChangeTitle}
              onKeyDown={handleKeyPress}
              className="w-full px-3 py-2  rounded-md 
                   text-sm text-black
                   focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent
                   transition-all"
            />
          </div>
          <div className="border-t border-gray-700 dark:border-gray-300 my-3"></div>
          <ul className="space-y-1">
            <li>
              <button
                className="w-full flex items-center gap-3 px-3 py-2.5 text-sm 
                         hover:dark:bg-[rgb(47,138,100)] hover:bg-[rgb(110,206,250)]  rounded-md transition-colors text-left group"
              >
                <Copy />
                <span>Nhân đôi danh sách</span>
              </button>
            </li>

            <li>
              <button
                onClick={onDeleTeColumn}
                className="w-full flex items-center gap-3 px-3 py-2.5 text-sm text-red-400 
                         hover:dark:bg-[rgb(47,138,100)] hover:bg-[rgb(110,206,250)]  rounded-md transition-colors text-left group"
              >
                <Trash2 />
                <span>Xóa danh sách</span>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </>,
    document.body
  );
}

export default ModalEditColumn;
