// output/VueJS-Trello-Board/src/components/task/ModalEditTask.vue
<script setup lang="js">
import { ref, computed, watch } from "vue"
import { Copy, Trash2, X } from "lucide-vue-next"
import { caculatePositionModal } from "../../utils/caculatePositionModal"
import { formatDate } from '../../utils/date'
defineOptions({ inheritAttrs: false })

const props = defineProps({
  selectTask: {
    type: Object,
    required: true,
  },
  selectTaskInColumnId: {
    type: String,
    required: true,
  },
  modalPosition: {
    type: Object,
    required: true,
  },
})

const emit = defineEmits([
  "closeEditTaskModal",
  "handleDeleteTask",
  "handleEditTask",
])

const inputTitle = ref("")
const inputDesc = ref("")
const inputPriority = ref("")

const modalSize = {
  width: 450,
  height: 380,
}


const position = computed(() =>
  caculatePositionModal(props.modalPosition, modalSize, 20)
)

const modalStyles = computed(() => ({
  top: position.value.top + "px",
  left: position.value.left + "px",
  width: modalSize.width + "px",
  height: modalSize.height + "px",
}))

const isActiveSaveBtn = computed(() => {
  if (!inputTitle.value.trim()) return true
  const hasChanges =
    inputTitle.value !== props.selectTask.title ||
    inputDesc.value !== props.selectTask.description ||
    inputPriority.value !== props.selectTask.priority
  return !hasChanges
})

const handleSubmit = () => {
  const newTaskData = {}

  if (inputTitle.value.trim())
    newTaskData.title = inputTitle.value.trim()

  if (inputDesc.value !== props.selectTask.description)
    newTaskData.description = inputDesc.value

  if (inputPriority.value.trim())
    newTaskData.priority = inputPriority.value

  if (Object.keys(newTaskData).length > 0) {
    emit("handleEditTask", newTaskData, props.selectTask.id, props.selectTaskInColumnId)
    emit("closeEditTaskModal")
  }
}

const handleDelete = () => {
  emit("handleDeleteTask", props.selectTask.id, props.selectTaskInColumnId)
}

const handleClose = () => {
  emit("closeEditTaskModal")
}

watch(
  () => props.selectTask,
  (newTask) => {
    if (!newTask) return
    inputTitle.value = newTask.title
    inputDesc.value = newTask.description
    inputPriority.value = newTask.priority
  },
  { immediate: true }
)

</script>

<template>
  <div class="fixed inset-0 z-50">
    <div class="absolute inset-0 bg-app-overlay" @click="handleClose"></div>
    <div class="absolute z-50" :style="modalStyles">
      <div class="flex h-full w-full flex-col rounded-2xl overflow-hidden text-sm bg-black/20  shadow-[0_18px_40px_rgba(15,23,42,0.18)]">
        <div class="flex flex-1  text-sm bg-transparent ">
          <div
            class="flex-1 flex flex-col gap-3 min-w-0 bg-app-bg-task px-3 py-3 rounded-2xl shadow-2xl border border-app-border-column text-app-text-main">
            <h3 class="text-sm font-semibold py-2 text-center">
              Chỉnh sửa task
            </h3>
            <div class="flex flex-col gap-1">
              <label class="text-xs font-medium text-app-text-sub">
                Title
              </label>
              <input v-model="inputTitle" type="text" placeholder="Enter task title"
                class="w-full px-3 py-2 rounded-lg border border-app-border-task bg-app-bg-modal text-sm text-app-text-main placeholder:text-app-text-muted focus:outline-none focus:ring-2 focus:ring-app-brand focus:border-app-brand transition-shadow" />
            </div>
            <div class="flex flex-col gap-1">
              <label class="text-xs font-medium text-app-text-sub">
                Mức độ ưu tiên
              </label>
              <select v-model="inputPriority"
                class="w-full px-3 py-2 rounded-lg border border-app-border-task bg-app-bg-modal text-sm text-app-text-main focus:outline-none focus:ring-2 focus:ring-app-brand focus:border-app-brand transition-shadow">
                <option value="High">High (Cao)</option>
                <option value="Medium">Medium (Trung bình)</option>
                <option value="Low">Low (Thấp)</option>
              </select>
            </div>
            <div class="flex flex-col gap-1">
              <label class="text-xs font-medium text-app-text-sub">
                Description
              </label>
              <textarea v-model="inputDesc" rows="4" placeholder="Nhập nội dung công việc..."
                class="w-full px-3 py-2 rounded-lg border border-app-border-task bg-app-bg-modal text-sm text-app-text-main placeholder:text-app-text-muted focus:outline-none focus:ring-2 focus:ring-app-brand focus:border-app-brand transition-shadow resize-none"></textarea>
            </div>
            <p class="mt-1 text-[11px] text-app-text-muted">
              Ngày tạo: {{ formatDate(props.selectTask.createdAt) }}
            </p>
          </div>
          <div class="w-40 flex flex-col justify-between gap-3 px-2 pt-16 pb-4">
            <div class="space-y-2">
              <button type="button"
                class="w-full flex items-center gap-2 px-3 py-2 rounded-xl shadow-2xl border border-app-border-column text-app-text-main bg-app-brand-soft hover:bg-app-brand-strong transition-colors">
                <Copy class="w-4 h-4" />
                <span class="text-xs font-medium">Nhân đôi task</span>
              </button>
              <button type="button" @click="handleDelete"
                class="w-full flex items-center gap-2 px-3 py-2 rounded-xl shadow-2xl border border-app-border-column bg-app-brand-soft text-app-text-main hover:bg-app-danger transition-colors">
                <Trash2 class="w-4 h-4" />
                <span class="text-xs font-medium">Xóa task</span>
              </button>
            </div>
            <div class="space-y-2 pt-2 border-t border-app-border-column">
              <button type="button" @click="handleSubmit" :disabled="!isActiveSaveBtn" :class="[
                'w-full px-3 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-colors shadow-2xl border border-app-border-column',
                isActiveSaveBtn
                  ? 'bg-app-brand-soft text-app-text-muted cursor-not-allowed opacity-70'
                  : 'bg-app-brand text-white hover:bg-app-brand-strong',
              ]">
                Lưu thay đổi
              </button>
              <button type="button" @click="handleClose"
                class="w-full px-3 py-2 rounded-xl shadow-2xl border border-app-border-column text-xs sm:text-sm font-medium bg-app-bg-board text-app-text-main hover:bg-app-brand-strong transition-colors">
                Hủy
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// output/mini-trello-project/src/components/task-card/ModalEditTask.jsx
import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { createPortal } from "react-dom";
import { formatDate } from "../../utils/Date";
import { useContext } from "react";
import { BoardContext } from "../../contexts/boardContext";

const ModalEditTask = ({ task, isOpen, onClose }) => {
  const { handleUpdateTask } = useContext(BoardContext);

  const [title, setTitle] = useState(task?.title || "");
  const [description, setDescription] = useState(task?.description || "");
  const [priority, setPriority] = useState(task?.priority || "Medium");
  const [activeSubmit, setActiveSubmit] = useState(true);

  useEffect(() => {
    const titleChanged = title.trim() && title.trim() !== task.title;
    const descChanged = description.trim() !== task.description;
    const priorityChanged = priority.trim() !== task.priority;
    
    if (titleChanged || descChanged || priorityChanged) {
      setActiveSubmit(false);
    } else {
      setActiveSubmit(true);
    }
  }, [title, description, priority, task]);

  const handleSubmit = () => {
    if (title.trim()) {
      handleUpdateTask({
        ...task,
        title: title.trim(),
        description: description.trim(),
        priority: priority,
      });
      onClose();
    }
  };

  if (!isOpen) return null;

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div
        className="bg-white text-black border border-black 
      dark:bg-black dark:border-white dark:text-white
      rounded-xl shadow-2xl w-full max-w-lg"
      >
        <div className="flex items-center justify-between p-5 border-b">
          <h3 className="text-lg font-semibold">Chỉnh sửa Task</h3>
          <button onClick={onClose}>
            <X size={20} />
          </button>
        </div>

        <div className="p-5 space-y-4">
          <div>
            <label className="block text-sm font-medium  mb-2">
              Tiêu đề <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Nhập tiêu đề task..."
              className="w-full px-4 py-2 border text-black border-black dark:border-none rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500  dark:focus:ring-yellow-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-2">Mô tả</label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Nhập mô tả chi tiết..."
              rows="4"
              className="w-full text-black px-4 py-2 border border-black dark:border-none rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-yellow-500 focus:border-transparent resize-none"
            />
          </div>

          <div>
            <label className="block text-sm font-medium mb-2">Độ ưu tiên</label>
            <div className="flex gap-2">
              {["Low", "Medium", "High"].map((p) => (
                <button
                  key={p}
                  onClick={() => setPriority(p)}
                  className={`flex-1 py-2 px-4 rounded-lg font-medium text-sm transition-all ${
                    priority === p
                      ? p === "High"
                        ? "bg-red-100 text-red-700 border-2 border-red-300"
                        : p === "Medium"
                        ? "bg-yellow-100 text-yellow-700 border-2 border-yellow-300"
                        : "bg-green-100 text-green-700 border-2 border-green-300"
                      : "bg-gray-100 text-black border-2 border-transparent hover:bg-gray-300"
                  }`}
                >
                  {p}
                </button>
              ))}
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium  mb-2">Ngày tạo</label>
            <input
              type="text"
              readOnly
              value={formatDate(task.createdAt)}
              className="w-full px-4 py-2 border text-black border-black dark:border-none rounded-lg focus:outline-none "
            />
          </div>
        </div>

        <div className="flex gap-3 p-5 border-t border-gray-200">
          <button
            onClick={onClose}
            className="flex-1 px-4 py-2 bg-gray-100 text-gray-700 font-medium rounded-lg hover:bg-gray-200 transition-colors"
          >
            Hủy
          </button>
          <button
            disabled={activeSubmit}
            onClick={handleSubmit}
            className="flex-1 px-4 py-2 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
          >
            Lưu thay đổi
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
};

export default ModalEditTask;
