// output/mini-trello-project/src/components/column/AddColumn.jsx
import { useState } from "react";
import { Plus } from "lucide-react";

const AddColumn = ({onAddColumn}) => {
  const [isAdding, setIsAdding] = useState(false);
  const [title, setTitle] = useState('');

  const handleSubmit = () => {
    if(title.trim())
      onAddColumn(title.trim())
      setIsAdding(false)
      setTitle('')
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleSubmit();
    }
  };

  if (!isAdding) {
    return (
      <button
        onClick={() => setIsAdding(true)}
        className="bg-white text-black dark:bg-black dark:text-white hover:bg-gray-300  rounded-lg p-2 w-80 flex-shrink-0 transition-all flex items-center
         justify-center gap-2 border border-black dark:border-white hover:dark:bg-gray-700 h-fit"
      >
        <Plus size={20} />
        <span className="font-medium">Thêm cột mới</span>
      </button>
    );
  }

  return (
    <div className="bg-white text-black dark:bg-black dark:text-white border border-black dark:border-white
    rounded-xl p-4 w-80 flex-shrink-0 h-fit">
      <label className=" mb-2 block text-lg font-medium">Tên cột</label>
      <input
        type="text"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        onKeyPress={handleKeyPress}
        placeholder="VD: Đang Review..."
        className="w-full px-3 py-2 border text-black border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-yellow-500 text-sm"
        autoFocus
      />
      <div className="flex gap-2 mt-3">
        <button
          onClick={handleSubmit}
          className="flex-1 px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-700 transition-colors"
        >
          Thêm
        </button>
        <button
          onClick={() => {
            setIsAdding(false);
            setTitle('');
          }}
          className="px-4 py-2 border border-black dark:border-white hover:bg-gray-300 hover:dark:bg-gray-700   text-sm font-medium rounded-md  transition-colors"
        >
          Hủy
        </button>
      </div>
    </div>
  );
};

export default AddColumn

// output/VueJS-Trello-Board/src/components/ui/AddColumn.vue
<script setup lang="js">
import { X, Plus } from 'lucide-vue-next'
import { ref } from 'vue';


const inputName = ref('')
const isAddColumn = ref(false)

const emit = defineEmits(['handleAddColumn'])

const handleSubmit = () => {
  if (!inputName.value.trim())
    return;
  emit('handleAddColumn', inputName.value);
  isAddColumn.value = false;
  inputName.value = '';
}
</script>

<template>
  <div class="shrink-0 w-full max-w-xs sm:w-72 sm:min-w-72">

      <div v-if="isAddColumn" key="form" class="bg-app-bg-task rounded-2xl p-3 sm:p-4 shadow-sm
               border border-app-border-column flex flex-col gap-3">
        <input type="text" placeholder="Nhập tên cột" v-model="inputName" class="w-full px-3 py-2 rounded-xl
                 border border-app-border-column
                 bg-app-bg-modal
                 placeholder:text-app-text-muted
                 text-sm text-app-text-main
                 focus:outline-none focus:ring-2
                 focus:ring-app-brand focus:border-app-brand
                 transition-shadow" @keyup.enter="handleSubmit" />

        <div class="flex justify-between items-center gap-2">
          <button @click="handleSubmit" type="button" class="flex-1 flex items-center justify-center gap-2
                   px-4 py-2 rounded-xl text-sm font-semibold
                   bg-app-brand text-white
                   hover:bg-app-brand-strong
                   transition-colors">
            Thêm cột
          </button>

          <button type="button" class="p-2 rounded-xl flex items-center justify-center
                   text-app-text-sub
                   hover:bg-app-brand-soft
                   transition-colors" @click="isAddColumn = false">
            <X class="w-5 h-5" />
          </button>
        </div>
      </div>
      <button v-else key="button" @click="isAddColumn = true" class="mt-1 flex w-full items-center justify-center gap-2
               font-semibold text-sm
               bg-app-brand-soft
               text-app-text-main
               border border-dashed border-app-border-column
               py-3 rounded-2xl
               hover:bg-app-brand-strong hover:text-white
               transition-colors">
        <Plus size="18" />
        <span>Thêm Cột</span>
      </button>
  </div>
</template>
